apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: nitin66/notification-service:v1
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
