version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  product-service:
    build: ./product-service
    ports:
      - "8080:8080"

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  notification-service:
    build: ./notification-service
    depends_on:
      - kafka