services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - microservices-net

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net
    depends_on:
      - zookeeper

  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKER: kafka:9092  # Added Kafka broker environment variable
    networks:
      - microservices-net
    depends_on:
      - kafka

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    environment:
      KAFKA_BROKER: kafka:9092  # Added Kafka broker environment variable
    networks:
      - microservices-net
    depends_on:
      - kafka

  notification-service:
    build: ./notification-service
    environment:
      KAFKA_BROKER: kafka:9092  # Added Kafka broker environment variable
    networks:
      - microservices-net
    depends_on:
      - kafka

networks:
  microservices-net:
    driver: bridge
