apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nitin66/order-service:v1
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
